[book]
authors = ["Stéphane ROBERT"]
language = "fr"
multilingual = false
src = "./"
title = "Awesome French Devops"
description = ""

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
# site-url = "/mdBook/"
git-repository-url = "https://github.com/stephrobert/awesome-french-devops"
git-repository-icon = "fa-github"
